version: '3'

services:
  database:
    container_name: database
    build: 
      context: ../database
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: on-failure

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - 8081:80
    links:
      - database:db
    restart: on-failure

  backend:
    container_name: backend
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    links:
      - database:mysql
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - database
      - backend
    ports:
      - 8080:80
    restart: on-failure

  reverse_proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - database
      - phpmyadmin
      - backend
      - frontend
    volumes:
      - ../reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80