version: '3'

services:
  database:
    container_name: database
    build: 
      context: ../database
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: on-failure

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - 8080:80
    links:
      - database:db

  backend:
    container_name: backend
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    links:
      - database:mysql

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - database
      - backend
    ports:
      - 80:80